const trainingModules = {
    video: [
        {
            id: "v1",
            title: "Identifying Suspicious Email Headers",
            description: "Learn how to analyze email headers to spot phishing attempts before opening them.",
            duration: "4 mins",
            level: "Beginner",
            thumbnail: "https://i.postimg.cc/rpNcf706/email-header.jpg",
            type: "video",
            popular: true,
            videoUrl: "https://www.youtube.com/embed/U7tbJVSInvo?si=Y8y89nIyVV2rE7F0"
        },
        {
            id: "v2",
            title: "Spotting Fake URLs and Domains",
            description: "Master the techniques to identify malicious URLs and lookalike domains.",
            duration: "6 mins",
            level: "Intermediate",
            thumbnail: "https://i.postimg.cc/bwQjv4RG/fake-url.jpg",
            type: "video",
            popular: true,
            videoUrl: "https://www.youtube.com/embed/Th7nu3aTqLs?si=aaUqKZJKswcE-Ifo"
        },
        {
            id: "v3",
            title: "Social Engineering Tactics Explained",
            description: "Understand the psychological tricks attackers use to manipulate victims.",
            duration: "7 mins",
            level: "Intermediate",
            thumbnail: "https://i.postimg.cc/MT3C4wzL/social-eng.jpg",
            type: "video",
            popular: false,
            videoUrl: "https://www.youtube.com/embed/v7VTJhkJUUY?si=zVGzpVN1xHKcw09G"
        },
        {
            id: "v4",
            title: "Protecting Your Digital Identity",
            description: "Essential practices to safeguard your personal information online.",
            duration: "14 mins",
            level: "Advanced",
            thumbnail: "https://placehold.co/400x225/112240/64ffda?text=Digital+Identity",
            type: "video",
            popular: false,
            videoUrl: "https://www.youtube.com/embed/HMJJygiOjhk?si=bMy1vDBLEntvA1R7"
        },
        {
            id: "v5",
            title: "Advanced Email Security Features",
            description: "Learn how to leverage built-in security features in modern email clients.",
            duration: "14 min",
            level: "Advanced",
            thumbnail: "https://placehold.co/400x225/112240/64ffda?text=Email+Security",
            type: "video",
            popular: false,
        },
    ],
    text: [
        {
            id: "t1",
            title: "The Anatomy of a Phishing Email",
            description: "A comprehensive breakdown of common elements found in phishing attempts.",
            readTime: "5 min read",
            level: "Beginner",
            icon: "mail",
            type: "text",
            popular: true,
        },
        {
            id: "t2",
            title: "Red Flags in Business Email Compromise",
            description: "Learn to identify suspicious requests from seemingly legitimate business contacts.",
            readTime: "8 min read",
            level: "Intermediate",
            icon: "alert",
            type: "text",
            popular: true,
        },
        {
            id: "t3",
            title: "Phishing Response Protocol",
            description: "Step-by-step guide on what to do when you encounter a suspected phishing attempt.",
            readTime: "6 min read",
            level: "Beginner",
            icon: "shield",
            type: "text",
            popular: false,
        },
        {
            id: "t4",
            title: "Secure Password Management",
            description: "Best practices for creating and managing strong, unique passwords.",
            readTime: "7 min read",
            level: "Beginner",
            icon: "lock",
            type: "text",
            popular: false,
        },
        {
            id: "t5",
            title: "Advanced Threat Analysis",
            description: "Technical deep-dive into analyzing suspicious emails and attachments.",
            readTime: "12 min read",
            level: "Advanced",
            icon: "search",
            type: "text",
            popular: false,
        },
    ],
}

export default trainingModules
